name = "Notrack"
license = "GPLv3"
licenselink = "https://github.com/gevhaz/hugo-theme-notrack/blob/master/LICENSE"
description = "A libre hugo personal webpage theme without reliance on third parties and no tracking."
homepage = "https://github.com/gevhaz/hugo-theme-notrack"
tags = ["minimal", "personal", "responsive", "libre", "flexbox"]
features = ["gallery", "events", "resume", "drop-down menu"]
min_version = "0.70.0"

[author]
  name = "Linlin Yu"
  homepage = "https://github.com/artsglobal"
